puts "We are about to destroy the entire DataBase, please remain calm"
Restaurant.destroy_all
puts ">> Restaurants were all destroyed"
puts ""
# User.destroy_all
# puts ">> Users were all destroyed"
#  puts ""
#  Comment.destroy_all
#  puts ">> Comments were all destroyed"
#  puts ""
#  puts ""

# # puts ">> We add some games :)"




 Restaurant.create(name:"Chez Françoise",country:"Portugal", address: "122 Rue Nollet, Paris",city:"Paris",description: "un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française", category: "française", stars: 5,photo: "https://u.tfstatic.com/restaurant_photos/249/6249/169/612/Terrasse-du-restaurant.jpg",price_avg: 45)
 Restaurant.create(name:"Pitalla",country:"France",address: "22 Rue de Miromesnil, Paris",city:"Paris",description: "un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française un restaurant de la cuisine indienne un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française", category: "indienne", stars: 3,photo: "https://u.tfstatic.com/restaurant_photos/249/6249/169/612/Terrasse-du-restaurant.jpg",price_avg: 50)
 Restaurant.create(name:"Havana café",country:"France", address: "01 Rue de Miromesnil, Paris",city:"Paris",description: "un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française un restaurant de la cuisine cubaine un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française", category: "cubaine", stars: 4,photo: "https://u.tfstatic.com/restaurant_photos/249/6249/169/612/Terrasse-du-restaurant.jpg",price_avg: 45)
 Restaurant.create(name:"Pitalla",country:"France",address: "54 avenue chandon, gennevilliers",city:"gennevilliers",description: "un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française un restaurant de la cuisine indienne un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française", category: "indienne", stars: 3,photo: "https://u.tfstatic.com/restaurant_photos/249/6249/169/612/Terrasse-du-restaurant.jpg",price_avg: 45)
 Restaurant.create(name:"Havana café",country:"France", address: "148 Rue du Faubourg Saint-Martin,paris",city:"Paris",description: "un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française un restaurant de la cuisine cubaine un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française", category: "argerie", stars: 4,photo: "https://u.tfstatic.com/restaurant_photos/249/6249/169/612/Terrasse-du-restaurant.jpg",price_avg: 65)
 Restaurant.create(name:"Chez Françoise",country:"Cuba", address: "14 rue valiton,clichy",city:"clichy",description: "un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française un restaurant de la cuisine française un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française", category: "française", stars: 5,photo: "https://u.tfstatic.com/restaurant_photos/249/6249/169/612/Terrasse-du-restaurant.jpg",price_avg: 75)
 Restaurant.create(name:"Pitalla",country:"France",address: "Aérogare des invalides,paris",city:"Paris",description: "un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française un restaurant de la cuisine indienne un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française", category: "argentine", stars: 3,photo: "https://u.tfstatic.com/restaurant_photos/249/6249/169/612/Terrasse-du-restaurant.jpg",price_avg: 95)
 Restaurant.create(name:"Havana café",country:"Portugal", address: "62 Rue Caulaincourt,paris",city:"Paris",description: "un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française un restaurant de la cuisine cubaine un restaurant de la cuisine française,un restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine françaiseun restaurant de la cuisine française", category: "canadienne", stars: 4,photo: "https://u.tfstatic.com/restaurant_photos/249/6249/169/612/Terrasse-du-restaurant.jpg",price_avg: 85)
 # curl -H "user-key:d4c0cc308f7033ff4644976d897bb815" https://developers.zomato.com/api/v2.1/cities\?q\=Denver
